<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="3.1.4" />
    <PackageReference Include="Microsoft.FASTER.Core" Version="2.6.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Stormancer.Raft\Stormancer.Raft.csproj" />
  </ItemGroup>

</Project>
